kubeApiServerAddress: http://10.151.41.16:8080

physicalCluster:
  skuTypes:
    K80:
      gpu: 1
      cpu: 4
      memory: 8192Mi
  cellTypes:
    K80-2GPU:
      childCellType: K80
      childCellNumber: 2
    K80-NODE:
      childCellType: K80-2GPU
      childCellNumber: 2
      isNodeLevel: true
    2-K80-NODE:
      childCellType: K80-NODE
      childCellNumber: 2
    3-K80-NODE:
      childCellType: K80-NODE
      childCellNumber: 3

  physicalCells:
  - cellType: 3-K80-NODE
    cellChildren:
    - cellAddress: 10.151.41.19
    - cellAddress: 10.151.41.25
      pinnedCellId: VC2-K80
    - cellAddress: 10.151.41.26
  - cellType: 2-K80-NODE
    cellChildren:
    - cellAddress: 10.151.41.23
    - cellAddress: 10.151.41.24

virtualClusters:
  VC1:
    virtualCells:
    - cellType: 3-K80-NODE.K80-NODE
      cellNumber: 1
  VC2:
    virtualCells:
    - cellType: 3-K80-NODE.K80-NODE
      cellNumber: 1
    pinnedCells:
    - pinnedCellId: VC2-K80
  default:
    virtualCells:
    - cellType: 2-K80-NODE
      cellNumber: 1